# This is a basic workflow to help you get started with Actions

name: Build and publish images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      REGISTRY: ghcr.io
      CNPG_TAG: 16.2
      PGVECTORS_TAG: 0.2.1
      TARGETARCH: amd64
      IMAGE_NAME: ${{ github.repository }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:cnpg-vectors"
          push: true
          tags: ghcr.io/jackrh/cnpg-vectors:${{ env.CNPG_TAG }}
          #labels: jackrh/cnpg-vectors
          build-args: |
            CNPG_TAG=${{ env.CNPG_TAG }}
            PGVECTORS_TAG=${{ env.PGVECTORS_TAG }}
            TARGETARCH=${{ env.TARGETARCH }}
